export const aiModels = [
  { id: 'gpt-5', name: 'GPT-5 (Omni-Reasoning)', provider: 'OpenAI', badge: 'High Precision', icon: 'Sparkles' },
  { id: 'claude-3-7', name: 'Claude 3.7 Sonnet (Hybrid)', provider: 'Anthropic', badge: 'Deep Reflection', icon: 'Brain' },
  { id: 'gemini-2-flash', name: 'Gemini 2.0 Flash Pro', provider: 'Google AI', badge: 'Ultra Fast', icon: 'Zap' },
];

export const promptSuggestions = [
  {
    id: 1,
    title: 'Analyze Competitor Landscape',
    description: 'Deep dive into OpenAI vs Anthropic vs DeepSeek architecture & market positioning.',
    icon: 'Building2',
    category: 'Market Intelligence',
    depth: 'Deep',
  },
  {
    id: 2,
    title: 'Research Latest AI Agent Trends',
    description: 'Autonomous reasoning, self-reflection loops, and multi-agent coordination frameworks.',
    icon: 'TrendingUp',
    category: 'AI Engineering',
    depth: 'Expert',
  },
  {
    id: 3,
    title: 'Compare Vector Databases',
    description: 'Benchmark Qdrant vs Pinecone vs Milvus vs pgvector on 10M embeddings scale.',
    icon: 'Database',
    category: 'Tech Evaluation',
    depth: 'Standard',
  },
  {
    id: 4,
    title: 'Generate Market Research Report',
    description: 'Comprehensive analysis on Autonomous Coding Assistants market growth 2026-2030.',
    icon: 'FileText',
    category: 'Industry Report',
    depth: 'Deep',
  },
];

export const agentSteps = [
  {
    id: 1,
    key: 'planner',
    name: 'Planner',
    description: 'Decomposing research goal into 8 targeted sub-queries',
    icon: 'Kanban',
    status: 'completed',
    timestamp: '12:44:02',
    logs: ['Sub-query 1: Neural network architectures', 'Sub-query 2: Benchmark comparisons', 'Targeting 14 web domains'],
  },
  {
    id: 2,
    key: 'search',
    name: 'Search Engine',
    description: 'Querying Google Search, DuckDuckGo, and Bing APIs',
    icon: 'Search',
    status: 'completed',
    timestamp: '12:44:15',
    logs: ['42 search result URLs retrieved', 'Filtered 12 duplicate & low quality links'],
  },
  {
    id: 3,
    key: 'web_reader',
    name: 'Website Reader',
    description: 'Scraping & extracting markdown from target web pages',
    icon: 'Globe',
    status: 'completed',
    timestamp: '12:44:30',
    logs: ['Scraped openai.com/research', 'Extracted blogs from techcrunch.com', 'Cleaned 180,000 tokens of raw text'],
  },
  {
    id: 4,
    key: 'github_analyzer',
    name: 'GitHub Analyzer',
    description: 'Parsing repository AST, READMEs, and open issues',
    icon: 'Github',
    status: 'completed',
    timestamp: '12:44:50',
    logs: ['Inspected github.com/langchain-ai/langchain', 'Analyzed repo auto-gpt/AutoGPT stars: 168k', 'Extracted benchmark scripts'],
  },
  {
    id: 5,
    key: 'paper_analyzer',
    name: 'Paper Analyzer',
    description: 'Ingesting ArXiv PDFs and LaTeX formulas',
    icon: 'BookOpen',
    status: 'completed',
    timestamp: '12:45:10',
    logs: ['Parsed ArXiv:2401.09823 [cs.AI]', 'Extracted 14 mathematical theorems', 'Cross-referenced citation network'],
  },
  {
    id: 6,
    key: 'data_analysis',
    name: 'Data Analysis',
    description: 'Synthesizing quantitative metrics & performance charts',
    icon: 'BarChart2',
    status: 'active',
    timestamp: '12:45:30',
    logs: ['Computing memory latency benchmarks', 'Building side-by-side comparison matrix'],
  },
  {
    id: 7,
    key: 'reflection',
    name: 'Reflection Engine',
    description: 'Self-correcting hallucinations & verification of claims',
    icon: 'RefreshCw',
    status: 'pending',
    timestamp: 'Waiting',
    logs: ['Pending verification step'],
  },
  {
    id: 8,
    key: 'report_generation',
    name: 'Report Generation',
    description: 'Drafting structured PDF/Markdown report with executive insights',
    icon: 'FileCheck',
    status: 'pending',
    timestamp: 'Waiting',
    logs: ['Pending final output compilation'],
  },
];

export const sampleChatHistory = [
  {
    id: 'msg-1',
    sender: 'user',
    text: 'Research the current state of Self-Evolving Autonomous AI Agents in 2026.',
    time: '12:42 PM',
  },
  {
    id: 'msg-2',
    sender: 'ai',
    text: 'I have launched an **Autonomous Deep Research Pipeline** to investigate Self-Evolving AI Agents across 5 core dimensions:\n\n1. **Self-Correction & Reflection Loops**: Dynamic prompt refinement and automated code execution validation.\n2. **Long-Term Memory Architectures**: Vector embeddings (Qdrant/Milvus) combined with graph databases.\n3. **Multi-Agent Swarm Orchestration**: Hierarchical task delegation (Planner -> Execution -> Judge).\n4. **Tool Use & Sandbox Execution**: Secure Docker & WebAssembly runtime environments.\n5. **Empirical Benchmarks**: Performance comparisons on SWE-bench, GAIA, and HumanEval.\n\nHere is the live step-by-step progress update:',
    time: '12:43 PM',
    sources: [
      { name: 'ArXiv Papers', url: 'https://arxiv.org', score: '99%' },
      { name: 'GitHub Repositories', url: 'https://github.com', score: '97%' },
      { name: 'OpenAI Blog', url: 'https://openai.com', score: '95%' },
    ],
    confidence: 0.984,
    reflectionNotes: 'Verified 42 citations against ArXiv preprints. No hallucinated citations detected in paper analysis module.',
  },
];

export const mockReport = {
  id: 'rep-8842',
  title: 'Self-Evolving Autonomous Research Agents: Architecture, Benchmarks & Future Trajectory',
  subtitle: 'A Comprehensive Deep Technical Audit & Competitive Analysis',
  topic: 'Autonomous Research Agents',
  date: 'August 7, 2026',
  author: 'ResearchMind AI Swarm',
  confidenceScore: 98.4,
  citationCount: 42,
  readingTime: '12 min read',
  depth: 'Expert',
  executiveSummary: `Autonomous AI Research Agents represent a paradigm shift from simple LLM query-response loops to self-directed, goal-oriented cognitive pipelines. By combining iterative reasoning trees, web scraping tools, repository static analysis, and rigorous self-reflection verification modules, autonomous agents can perform literature reviews and tech evaluations in minutes that previously required weeks of human analysis.

Key insights indicate a 400% increase in autonomous agent deployments across Fortune 500 engineering teams in 2026, primarily driven by self-correcting code loops and hybrid vector-graph long-term memory systems.`,
  findings: [
    {
      heading: '1. Dynamic Self-Reflection & Contradiction Detection',
      content: 'Modern agents utilize a dual-model architecture where an Executive Planner proposes hypotheses while a separate Critic/Judge model validates citations against primary web and paper sources. This reduces hallucination rates below 0.5%.',
    },
    {
      heading: '2. Multi-Modal Repository & Whitepaper Parsing',
      content: 'Integration of AST parsers and OCR whitepaper ingestion allows agents to run benchmark scripts directly in sandbox containers, verifying performance claims in real time rather than relying solely on textual claims.',
    },
    {
      heading: '3. Long-Term Vector Memory & Knowledge Graphs',
      content: 'By pairing high-density embeddings (1536-dim) with semantic graph nodes, agents maintain persistent state across multi-day research tasks without losing context constraints.',
    },
  ],
  comparisonTable: [
    { framework: 'ResearchMind AI', reasoning: 'Self-Evolving Swarm', speed: '2.4s/step', accuracy: '98.4%', cost: '$0.04/task' },
    { framework: 'AutoGPT 2.0', reasoning: 'Single-Loop Agent', speed: '5.8s/step', accuracy: '89.1%', cost: '$0.12/task' },
    { framework: 'LangChain DeepResearch', reasoning: 'DAG Workflow', speed: '4.1s/step', accuracy: '92.5%', cost: '$0.08/task' },
    { framework: 'CrewAI Enterprise', reasoning: 'Role-Based Crew', speed: '3.9s/step', accuracy: '94.0%', cost: '$0.07/task' },
  ],
  recommendations: [
    'Standardize on hybrid vector-graph databases for persistent research memory.',
    'Implement Docker sandbox runtimes to safely run generated code benchmarks.',
    'Deploy automated reflection checks prior to publishing final executive reports.',
  ],
  references: [
    { title: 'Attention Is All You Need & Beyond: Scalable Reasoners in 2026', source: 'ArXiv:2603.09121', link: 'https://arxiv.org', rating: '99% Match' },
    { title: 'SWE-bench Unified: Evaluating Autonomous Coding Agents', source: 'GitHub Benchmark Suite', link: 'https://github.com', rating: '97% Match' },
    { title: 'OpenAI Autonomous Agent Systems Technical Report', source: 'OpenAI Research', link: 'https://openai.com', rating: '96% Match' },
    { title: 'DeepSeek-V3 Infrastructure & Reasoning Tokens', source: 'DeepSeek Research', link: 'https://deepseek.com', rating: '94% Match' },
  ],
};

export const researchHistory = [
  {
    id: 'res-101',
    topic: 'Self-Evolving Autonomous Research Agent Systems',
    date: '2026-08-07',
    status: 'Completed',
    duration: '2m 14s',
    sourcesCount: 42,
    confidence: '98.4%',
    depth: 'Expert',
  },
  {
    id: 'res-102',
    topic: 'Qdrant vs Pinecone vs Milvus Benchmark Analysis',
    date: '2026-08-06',
    status: 'Completed',
    duration: '1m 45s',
    sourcesCount: 28,
    confidence: '96.2%',
    depth: 'Deep',
  },
  {
    id: 'res-103',
    topic: 'Small Language Models (SLMs) on Edge Devices (Mobile/IoT)',
    date: '2026-08-05',
    status: 'Completed',
    duration: '3m 10s',
    sourcesCount: 35,
    confidence: '97.0%',
    depth: 'Deep',
  },
  {
    id: 'res-104',
    topic: 'Quantum Computing Encryption Break Timeline (2026-2035)',
    date: '2026-08-04',
    status: 'In Progress',
    duration: '1m 02s',
    sourcesCount: 19,
    confidence: '88.5%',
    depth: 'Expert',
  },
  {
    id: 'res-105',
    topic: 'Next.js 15 App Router vs Vite SPA Performance Audit',
    date: '2026-08-02',
    status: 'Completed',
    duration: '48s',
    sourcesCount: 14,
    confidence: '94.8%',
    depth: 'Standard',
  },
  {
    id: 'res-106',
    topic: 'Autonomous Code Review Agents Security Vulnerability Detection',
    date: '2026-07-30',
    status: 'Completed',
    duration: '4m 05s',
    sourcesCount: 51,
    confidence: '99.1%',
    depth: 'Expert',
  },
];

export const knowledgeItems = [
  {
    id: 'kn-1',
    title: 'Large Language Model Transformer Architecture',
    description: 'Decoder-only self-attention mechanism with RoPE positional embeddings, SwiGLU activations, and FlashAttention-3 memory optimizations.',
    tags: ['AI', 'LLM', 'Research', 'Architecture'],
    similarityScore: '98.8%',
    createdDate: '2026-08-01',
    tokens: 4200,
    domain: 'Core Machine Learning',
  },
  {
    id: 'kn-2',
    title: 'Autonomous Reflection & Self-Correction Loops',
    description: 'Iterative verification patterns where an agent evaluates its own output against ground-truth data sources before delivering final results.',
    tags: ['Agents', 'Reflection', 'Prompting'],
    similarityScore: '97.5%',
    createdDate: '2026-08-03',
    tokens: 2850,
    domain: 'Agentic Frameworks',
  },
  {
    id: 'kn-3',
    title: 'High-Density Vector Embeddings Indexing (HNSW)',
    description: 'Hierarchical Navigable Small World graphs for ultra-fast approximate nearest neighbor search across multi-million dimensional spaces.',
    tags: ['Database', 'Vector', 'HNSW', 'Search'],
    similarityScore: '95.2%',
    createdDate: '2026-07-28',
    tokens: 3100,
    domain: 'Vector Storage',
  },
  {
    id: 'kn-4',
    title: 'SWE-bench Coding Agent Evaluation Metric',
    description: 'Benchmark dataset evaluating AI models on resolving real-world GitHub issues across popular open-source Python repositories.',
    tags: ['Benchmark', 'Coding', 'GitHub', 'Evaluation'],
    similarityScore: '94.0%',
    createdDate: '2026-07-25',
    tokens: 1900,
    domain: 'Model Benchmarking',
  },
  {
    id: 'kn-5',
    title: 'Graph RAG: Combining Knowledge Graphs with Vector Search',
    description: 'Hybrid retrieval augmented generation leveraging structured entity graphs alongside unstructured dense text vectors for deep reasoning.',
    tags: ['RAG', 'Knowledge Graph', 'Search'],
    similarityScore: '93.6%',
    createdDate: '2026-07-20',
    tokens: 5400,
    domain: 'Retrieval Systems',
  },
  {
    id: 'kn-6',
    title: 'FastAPI High-Performance Async Backend Integration',
    description: 'Building non-blocking web servers with Python Pydantic v2 validation, Starlette routing, and Server-Sent Events (SSE) streaming.',
    tags: ['FastAPI', 'Python', 'Backend', 'API'],
    similarityScore: '91.2%',
    createdDate: '2026-07-15',
    tokens: 2100,
    domain: 'System Architecture',
  },
];

export const userProfile = {
  name: 'Dr. Sarah Connor',
  email: 'sarah.connor@researchmind.ai',
  avatar: null, // Profile photo removed in favor of monochrome icon logo
  role: 'Principal AI Researcher',
  organization: 'Cyberdyne AI Systems',
  stats: {
    totalResearch: 120,
    reportsGenerated: 85,
    knowledgeItems: 350,
    computeHours: '42.5h',
    accuracyRating: '99.2%',
  },
  achievements: [
    { title: 'Research Master', description: 'Completed over 100 deep autonomous research agent tasks', icon: 'Award', color: 'text-white', date: 'Unlocked' },
    { title: 'AI Explorer', description: 'Evaluated 50+ whitepapers and GitHub codebases', icon: 'Compass', color: 'text-zinc-200', date: 'Unlocked' },
    { title: 'Knowledge Builder', description: 'Added 300+ vector memory embeddings to long-term database', icon: 'Database', color: 'text-zinc-300', date: 'Unlocked' },
    { title: 'Reflection Guru', description: 'Achieved zero hallucinated citations across 50 consecutive runs', icon: 'CheckCircle2', color: 'text-zinc-400', date: 'Unlocked' },
  ],
};
